/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2-dev */

#include "Macro.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(windy_keyboards_Macro, windy_keyboards_Macro, AUTO)


PB_BIND(windy_keyboards_Micro, windy_keyboards_Micro, AUTO)